version: "3"
services:
    db:
        image: mysql:5.7
        container_name: db
        environment:
            MYSQL_ROOT_PASSWORD: my_secret_password
            MYSQL_DATABASE: app_db
            MYSQL_USER: db_user
            MYSQL_PASSWORD: db_user_pass
        ports:
        - "6033:3306"
        volumes:
        - ./data/db:/var/lib/mysql
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: pma
        links:
        - db
        environment:
            PMA_HOST: db
            PMA_PORT: 3306
            PMA_ARBITRARY: 1
        restart: always
        ports:
        - 8081:80
    routes-python:
        build: ./
        container_name: routes
        links:
            - "db"
        restart: always
        ports:
            - "5001:5000"
    grafana:
        build: grafana
        container_name: grafana
        links:
            - "db"
        environment:
            # - GF_DATABASE_HOST=db:3306
            # - GF_DATABASE_NAME=app_db
            # - GF_DATABASE_USER=db_user
            # - GF_DATABASE_PASSWORD=db_user_pass
            # - GF_DATABASE_TYPE=mysql
            - GF_PATHS_PROVISIONING=/app-grafana/provisioning
        restart: always
        ports:
            - '80:3000'