version: "3"
services:
    db:
        image: mysql:5.7
        container_name: db
        environment:
            MYSQL_ROOT_PASSWORD: my_secret_password
            MYSQL_DATABASE: app_db
            MYSQL_USER: db_user
            MYSQL_PASSWORD: db_user_pass
        ports:
        - "6033:3306"
        volumes:
        - ./data/db:/var/lib/mysql:/var/lib/mysql
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: pma
        links:
        - db
        environment:
            PMA_HOST: db
            PMA_PORT: 3306
            PMA_ARBITRARY: 1
        restart: always
        ports:
        - 8081:80
    osrm:
        build: ./
        container_name: osrm
        links:
            - "db"
        restart: always
        ports:
            - "5001:5000"
    grafana:
        image: grafana/grafana
        container_name: grafana
        links:
            - "db"
        environment:
            - GF_DATABASE_HOST=db:3306
            - GF_DATABASE_NAME=app_db
            - GF_DATABASE_USER=db_user
            - GF_DATABASE_PASSWORD=db_user_pass
            - GF_DATABASE_TYPE=mysql
        restart: always
        ports:
            - '80:3000'
    # valhalla:
    #     container_name: valhalla
    #     image: 'gisops/valhalla:latest'
    #     volumes:
    #         - ./data/valhalla:/custom_files
    #     ports:
    #         - 8002:8002
    #     environment:
    #       - tile_urls=http://download.geofabrik.de/europe/france-latest.osm.pbf
    #       - server_threads=2  # determines how many threads will be used to run the valhalla server
    #       - use_tiles_ignore_pbf=True  # load existing valhalla_tiles.tar directly
    #       - build_elevation=False  # build elevation with "True" or "Force": will download only the elevation for areas covered by the graph tiles
    #       - build_admins=False  # build admins db with "True" or "Force"
    #       - build_time_zones=False  # build timezone db with "True" or "Force"
    #       - build_tar=True  # build an indexed tar file from the tile_dir for faster graph loading times
    #       - force_rebuild=False  # forces a rebuild of the routing tiles with "True"