{
 "title": "Trajets",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "departure",
    "label": "Ville de départ",
    "query": "SELECT DISTINCT departure FROM routes"
   },
   {
    "name": "arrival",
    "label": "Point d'arrivée",
    "query": "SELECT DISTINCT arrival FROM routes"
   }
  ]
 },
 "panels": [
  {
   "title": "Temps Moyen",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT AVG(duration) as value FROM app_db.routes WHERE departure=${departure:doublequote} AND arrival=${arrival:doublequote}"
    }
   ]
  },
  {
   "title": "Diff avec/sans bouchon",
   "type": "stat",
   "gridPos": { "h": 8, "w": 7, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT MAX(duration) - MIN(duration) as value FROM app_db.routes WHERE departure=${departure:doublequote} AND arrival=${arrival:doublequote}"
    }
   ]
  },
  {
   "title": "Distance",
   "type": "stat",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT AVG(distance) as value FROM app_db.routes WHERE departure=${departure:doublequote} AND arrival=${arrival:doublequote}"
    }
   ]
  },
  {
   "title": "${departure:text} -> ${arrival:text}",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT $__time(date), duration / 60 FROM app_db.routes WHERE departure=${departure:doublequote} AND arrival=${arrival:doublequote}"
    }
   ]
  }
 ]
}